# To install:
#
#     pip install pre-commit
#
# To use:
#
#     pre-commit run -a --config .pre-commit-config-optional.yaml
#
# To update this file:
#
#     pre-commit autoupdate --config .pre-commit-config-optional.yaml
#
# See https://github.com/pre-commit/pre-commit

repos:
  - repo: https://github.com/ComPWA/mirrors-markdown-link-check
    rev: "v3.8.7"
    hooks:
      - id: markdown-link-check
        files: \.md$
