name: pre-commit (Optional)

on:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit-optional:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: "--all-files --config .pre-commit-config-optional.yaml"
